[package]
name = "ocelli"
version = "0.1.0"
edition = "2021"

[lib]
name = "ocelli"
path = "src/lib.rs"
crate-type = ["cdylib", "staticlib"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"